#!/bin/bash

# install the agent on Amazon Linux 2
sudo yum install amazon-cloudwatch-agent

# run the wizard
sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-config-wizard

# create some missing files
sudo mkdir -p /usr/share/collectd
sudo touch /usr/share/collectd/types.db

# options:

# Fetch the configuration from AWS Systems Manager Parameter Store
sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
  -a fetch-config -m ec2 \
  -c ssm:AmazonCloudWatch-linux -s

# Fetch the configuration from a local JSON file
sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
  -a fetch-config -m ec2 \
  -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s


``` 
This script installs and configures the Unified Amazon CloudWatch Agent on an Amazon Linux 2 EC2 instance. 
It launches the configuration wizard to define the metrics and logs to collect, creates the required collectd files, 
and provides options to load the agent configuration either from AWS Systems Manager Parameter Store 
or a local JSON configuration file before starting the agent.

```
